### ISSUE TITLE
Service Request by Donrie on behalf of Jessica and the RC team 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#27]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [x] Problem FULLY RESOLVED and Issue is Closed
- [x] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff 
Please advise how soon we may have access to the demographics in Monitoring.
Secondly, it may be something of a bug (albeit I sort of understand) the Research Coordinators are asking if there is any way that they can proceed with currently saved data in the IPA tracker even if someone is making changes to a strategy or IPA.    

**Please see email for reference  below:**


<blockquote type="cite" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: &quot;Times New Roman&quot;; font-size: 18px;"><div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>From:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;">Jessica Neufeld &lt;jn2434@columbia.edu&gt;<br></span></div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>Subject:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;"><b>Fwd: IPA Tracking</b><br></span></div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>Date:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;">September 7, 2021 at 4:17:12 PM EDT<br></span></div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>To:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;">Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br></span></div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>Cc:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;">Nicholas Bove &lt;nicholas.bove@einsteinmed.org&gt;<br></span></div><br><div><div class="">

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
--


<div class=""><div dir="ltr" class="">Hi Donrie and Nick, <div class=""><br class=""></div><div class="">I know the demographics section is still pending, but do you know if the programmer has an estimate for when it might be available? The Suffolk team has some demographic data and was having trouble finding the proper place to enter it (see below).</div><div class=""><br class=""></div><div class="">Another issue I ran into was if someone was making edits to the IPA at the same time someone ran a report, it affected the report. I know Emilia was making edits to C2 when Anna ran a report to get the total list of strategies and C2 was missing from her report output. </div><div class=""><br class=""></div><div class="">Best, </div><div class="">Jessica </div></div></div></div></div></div></blockquote><br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><br class="Apple-interchange-newline">

**Comment by dlounsbu** [comment]
Hi all:

I do not think what Jessica is talking about is a bug. When she says run reports, does she mean run a Data Download? She must. 

I think that, again, we need to inform users that they are working on a cloud-based platform that many people can access at once that is still being tested. 

It is best practice to be very deliberate about saving data and, regarding Downloading Data, staff should confirm that there are no important data updates pending at the time they wish to Download Data. 

My two cents. 

DL

**Comment by dlounsbu** [comment]
@donriepurcell 

Please try to keep all discussion about Jeff's demo fields in Issue #5

Best,
David

**Comment by jbazinet1111** [comment]
The demographics functionality is there for monitoring. It comes up automatically if you edit a measures monitoring record that has “Persons” as the unit of measure. Otherwise, if you want to override the “persons” requirement (say, for instance, if you put “people” or some other synonym as your unit of measure), you can check the box and enter the demographics data.

**Comment by dlounsbu** [comment]
From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Wednesday, September 8, 2021 11:07 AM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: IPA Tracker Support Request Form Submitted

IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Jessica   Neufeld

Email:  jn2434@columbia.edu

Phone:  212-853-8380


2. COUNTY

All counties


3. WHICH FEATURE(S):

REPORTING: Downloading data to create a table, figure or other summary report


4. BRIEF PROBLEM DESCRIPTION:

Know the demographics section is still pending, but do you know do you have an estimate for when it might be available? I ran into an issue when someone was making edits to the IPA at the same time I ran a report, it affected the report. I know a data coordinator was making edits to their C2 IPA and when I ran a report to downloaded the list of strategies, the report was missing C2. I have a copy of the report that shows this. If this is an issue, then clear guidance over when the site is updated or best time to run reports (i.e. uncommon times?) 


5. URGENCY:

50


6. ANYTHING ELSE TO SHARE: 

The preferred email and preferred phone number entries on this form are very finicky

**Comment by dlounsbu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal><b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman"'>From:</span></b><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
"Times New Roman"'> david lounsbury <br>
<b>Sent:</b> Wednesday, September 8, 2021 11:56 AM<br>
<b>To:</b> Jessica Neufeld &lt;jn2434@columbia.edu&gt;<br>
<b>Cc:</b> Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br>
<b>Subject:</b> RE: FW: IPA Tracker Support Request Form Submitted<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Got it. <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Well, we are now using a very powerful platform that is subject
to edits to its data, big and small, at virtually any moment. <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>To ensure the cleanest downloads, maybe give your staff a heads
up that you are going to download data for reporting, and ask them to complete
their data entry and edits before you do so. Something like that ?!!?<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Best and thanks,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>David<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='mso-outline-level:1'><b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'>From:</span></b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'> Jessica Neufeld [<a
href="mailto:jn2434@columbia.edu">mailto:jn2434@columbia.edu</a>] <br>
<b>Sent:</b> Wednesday, September 8, 2021 11:50 AM<br>
<b>To:</b> david lounsbury &lt;<a href="mailto:david.lounsbury@einsteinmed.org">david.lounsbury@einsteinmed.org</a>&gt;<br>
<b>Cc:</b> Donrie Purcell &lt;<a href="mailto:donrie.purcell@einsteinmed.org">donrie.purcell@einsteinmed.org</a>&gt;<br>
<b>Subject:</b> Re: FW: IPA Tracker Support Request Form Submitted<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This email comes from an external source; the   attachments and/or links may compromise our secure environment. Do not open   or click on suspicious emails. Please click on the “Phish Alert” button on   the top right of the Outlook dashboard to report any suspicious emails.
--




<p class=MsoNormal>Hi David,&nbsp; <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Yes, but this issue was I asked RCs to get a total list of
IPAs and the totals varied (this is why I also asked Donrie what his count
was).&nbsp;<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>As long as I know to triple check the totals, then I'll make
sure to wait and use the report that best reflects the IPAs.&nbsp;<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Best,<o:p></o:p></p>

<p class=MsoNormal>Jessica&nbsp;<o:p></o:p></p>


</body>

</html>
