### ISSUE TITLE
Service Request by Veronica Salvas for help with MONITORING Measures

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#31]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [x] Problem FULLY RESOLVED and Issue is Closed
- [x] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Wednesday, September 8, 2021 7:38 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: IPA Tracker Support Request Form Submitted

IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Veronica  Salvas

Email:  vsalvas@mhacg.org

Phone:  845 264 1765


2. COUNTY

Columbia


3. WHICH FEATURE(S):

MONITORING: Creating, updated or deleting information about an implemented SMART Strategy


4. BRIEF PROBLEM DESCRIPTION:

the metrics for IPA: Multi-county web-based training for MOUD providers are not up to date. They should be " 2.5 # of individuals receiving MOUD" # licensed providers registered for series (Columbia County) # licensed providers registered for series (Outside Columbia County) # licensed providers completing series (Columbia County) # licensed providers completing series (Outside Columbia County) # licensed providers registered for session 1 (Columbia County) # licensed providers completing session 1 (Columbia County) # licensed providers registered for session 2 (Columbia County) # licensed providers completing session 2 (Outside Columbia County) # licensed providers registered for session 3 (Columbia County) # licensed providers completing session 3 (Outside Columbia County) # licensed providers registered for session 4 (Columbia County) # licensed providers completing session 4 (Outside Columbia County) # licensed providers attending reporting the currently prescribe MOUD/MAT # licensed providers attending reporting they plan to prescribe MOUD/MAT Proportion of licensed providers attending who are not currently prescribing, but report intention to start prescribing MOUD/MAT 


5. URGENCY:

50


6. ANYTHING ELSE TO SHARE:

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, September 8, 2021 8:12 PM
To: vsalvas@mhacg.org
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: FW: IPA Tracker Support Request Form Submitted
Importance: High

Hi Veronica:

We have received your IPA Service Request and will be glad to assist you. 

It maybe be useful to arrange a short call or Zoom meeting to better understand what is needed. 

I could meet with you between 3pm-4pm, or maybe, Nick, you could follow up if that time is not convenient for Veronica??

Dr. Purcell is traveling tomorrow, but will be back on-line Friday. 

Hope to connect with you soon.

Best,
David

**Comment by dlounsbu** [comment]
From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Wednesday, September 8, 2021 7:29 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: IPA Tracker Support Request Form Submitted

IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Veronica  Salvas

Email:  vsalvas@mhacg.org

Phone:  845 264 1765


2. COUNTY

Columbia


3. WHICH FEATURE(S):

SPECIFICATION: Creating, updating, deleting information to define or describe a SMART Strategy


4. BRIEF PROBLEM DESCRIPTION:

The metrics for IPA Safer Prescribing C1 are not current. They should be: Home Study: # of licensed pharmacists registered Session 1 (Columbia County) Home Study: # of licensed pharmacists registered Session 1 (Other County) Home Study: # of licensed pharmacists registered Session 2 (Columbia County) Home Study: # of licensed pharmacists registered Session 2 (Other County) Home Study: # of licensed pharmacists registered Session 3 (Columbia County) Home Study: # of licensed pharmacists registered Session 3 (Other County) Home Study: # of licensed pharmacists registered Session 4 (Columbia County) Home Study: # of licensed pharmacists registered Session 4 (Other County) proportion of attendees indicating an intent to act, per specified session topics (ie, intent to enroll in NCAP if not enrolled; enroll in ESAP if not enrolled) Volume of Naloxone dispensed via pharmacies at the county level Live Event: # of licensed pharmacists registered (by session, by county and overall) Live Event: # of licensed pharmacists attended (by session, by county and overall)


5. URGENCY:

50


6. ANYTHING ELSE TO SHARE:

**Comment by dlounsbu** [comment]
> From: David Lounsbury [mailto:[noreply@qemailserver.com](mailto:noreply@qemailserver.com)]
> Sent: Wednesday, September 8, 2021 7:29 PM
> To: david lounsbury [david.lounsbury@einsteinmed.org](mailto:david.lounsbury@einsteinmed.org)
> Subject: IPA Tracker Support Request Form Submitted
> 
> IPA SERVICE REQUEST SUMMARY
> 
> 1. CONTACT INFORMATION:
> 
> Veronica Salvas
> 
> Email: [vsalvas@mhacg.org](mailto:vsalvas@mhacg.org)
> 
> Phone: 845 264 1765
> 
> 1. COUNTY
> 
> Columbia
> 
> 1. WHICH FEATURE(S):
> 
> SPECIFICATION: Creating, updating, deleting information to define or describe a SMART Strategy
> 
> 1. BRIEF PROBLEM DESCRIPTION:
> 
> The metrics for IPA Safer Prescribing C1 are not current. They should be: Home Study: # of licensed pharmacists registered Session 1 (Columbia County) Home Study: # of licensed pharmacists registered Session 1 (Other County) Home Study: # of licensed pharmacists registered Session 2 (Columbia County) Home Study: # of licensed pharmacists registered Session 2 (Other County) Home Study: # of licensed pharmacists registered Session 3 (Columbia County) Home Study: # of licensed pharmacists registered Session 3 (Other County) Home Study: # of licensed pharmacists registered Session 4 (Columbia County) Home Study: # of licensed pharmacists registered Session 4 (Other County) proportion of attendees indicating an intent to act, per specified session topics (ie, intent to enroll in NCAP if not enrolled; enroll in ESAP if not enrolled) Volume of Naloxone dispensed via pharmacies at the county level Live Event: # of licensed pharmacists registered (by session, by county and overall) Live Event: # of licensed pharmacists attended (by session, by county and overall)
> 
> 1. URGENCY:
> 
> 50
> 
> 1. ANYTHING ELSE TO SHARE:

Looks like Veronica has questions about who to navigate both the SPECIFICATION and the MONITORING features of the Tracker.

**Comment by dlounsbu** [comment]
From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Wednesday, September 8, 2021 7:35 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: IPA Tracker Support Request Form Submitted

IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Veronica  Salvas

Email:  vsalvas@mhacg.org

Phone:  845 264 1765


2. COUNTY

Columbia


3. WHICH FEATURE(S):

Some other feature


4. BRIEF PROBLEM DESCRIPTION:

The metrics, milestones, etc for IPA: OEND B3 are not up to date. Let me know how best to provide the correct info.


5. URGENCY:

50


6. ANYTHING ELSE TO SHARE:

**Comment by dlounsbu** [comment]
I meeting with Veronica to assist her is in order. 

I can try to reach her tomorrow around 3pm. Or, Nick, if you are free earlier, see if you can assist.

**Comment by dlounsbu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in'>


<p class=MsoNormal><b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman"'>From:</span></b><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
"Times New Roman"'> Veronica Salvas [mailto:vsalvas@mhacg.org] <br>
<b>Sent:</b> Wednesday, September 8, 2021 8:42 PM<br>
<b>To:</b> david lounsbury &lt;david.lounsbury@einsteinmed.org&gt;<br>
<b>Cc:</b> Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;; Nicholas Bove
&lt;nicholas.bove@einsteinmed.org&gt;<br>
<b>Subject:</b> Re: FW: IPA Tracker Support Request Form Submitted<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This   email comes from an external source; the attachments and/or links may   compromise our secure environment. Do not open or click on suspicious emails.   Please click on the “Phish Alert” button on the top right of the Outlook   dashboard to report any suspicious emails.
--




<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Thank
you.&nbsp; I am not available tomorrow afternoon.&nbsp; I could do Friday
sometime between 11 and 2, or next week Monday, Thursday and Friday are fairly
open for me.<o:p></o:p></span></p>


</body>

</html>

**Comment by NBOVE1** [comment]
Hi Veronica,
I’m available today 11AM-12PM, or tomorrow 11AM-12PM. Please let me know which would work best for you.
Thanks,
Nick

**Comment by NBOVE1** [comment]
Thanks very much Veronica!

I will review with Donrie. And I am making a note to circle back to you next week, Friday (9/17). 

To summarize our discussion and your excellent points – we (Einstein and those of use supporting the IPA Tracker tool) can and should be more proactive in providing coaches and county coalition staff with ‘data’ support. There is a need to help counties streamline their measures with their smart strategies. Specifically, there are often ‘Other’ Measures (other than Primary, Secondary, and Structural) that are nonsensical. 
Again, a pleasure to talk with you.

DL

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Friday, September 10, 2021 2:01 PM
To: Veronica Salvas <vsalvas@mhacg.org>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: RE: Columbia County metrics

Thanks very much Veronica!

I will review with Donrie. And I am making a note to circle back to you next week, Friday (9/17). 

To summarize our discussion and your excellent points – we (Einstein and those of use supporting the IPA Tracker tool) can and should be more proactive in providing coaches and county coalition staff with ‘data’ support. There is a need to help counties streamline their measures with their smart strategies. Specifically, there are often ‘Other’ Measures (other than Primary, Secondary, and Structural) that are nonsensical. 
Again, a pleasure to talk with you.

DL

David W. Lounsbury, PhD
Associate Professor, Epidemiology & Population Health
Associate Director, Patient-Centered Outcomes Research Training
Department of Epidemiology & Population Health
Division of Health Behavior Research and Implementation Science
Albert Einstein College of Medicine
David.Lounsbury@einsteinmed.org e-mail
718.839.7452 office
917.690.1020 cell
718.652.0418 fax

Office Address:
1300 Morris Park Avenue
Van Etten 3A2D (Wing A)
Bronx, NY USA 10461

Faculty Fellow:
Center for Systems and Community Design
CUNY Graduate School of Public Health & Health Policy

Faculty Affiliate (2019-2021):
Mary Ann Swetland Center for Environmental Health
School of Medicine, Case Western Reserve University

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, September 15, 2021 6:21 PM
To: Veronica Salvas <vsalvas@mhacg.org>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: RE: Columbia County metrics

Hi Veronica:

Just getting back to you about how best to streamline measures for Columbia County in the Tracker. 

You mentioned that you are responsible for just 3 IPAs. Who else should we engage about the others ? Danielle Hotaling and/or Lori Torgersen, PhD?

Best, 
David

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, September 15, 2021 8:08 PM
To: Veronica Salvas <vsalvas@mhacg.org>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: RE: Columbia County metrics
Importance: High

Hi Veronica:

Yes, we would like that!
We know that there are still structural, design and data management issues with the Tracker, so consultation with them will be very helpful to us and, we hope, useful to them, too!
Thank you!

David

PS – thank you for sharing your tracking spreadsheets. They are very elegant. We are referencing parts for some of our visualizing exercises with Tracker data.

**Comment by dlounsbu** [comment]
> From: david lounsbury
> Sent: Wednesday, September 15, 2021 8:08 PM
> To: Veronica Salvas [vsalvas@mhacg.org](mailto:vsalvas@mhacg.org)
> Cc: Donrie Purcell [donrie.purcell@einsteinmed.org](mailto:donrie.purcell@einsteinmed.org)
> Subject: RE: Columbia County metrics
> Importance: High
> 
> Hi Veronica:
> 
> Yes, we would like that!
> We know that there are still structural, design and data management issues with the Tracker, so consultation with them will be very helpful to us and, we hope, useful to them, too!
> Thank you!
> 
> David
> 
> PS – thank you for sharing your tracking spreadsheets. They are very elegant. We are referencing parts for some of our visualizing exercises with Tracker data.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal style='mso-outline-level:1'><b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'>From:</span></b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'> Veronica Salvas [<a
href="mailto:vsalvas@mhacg.org">mailto:vsalvas@mhacg.org</a>] <br>
<b>Sent:</b> Wednesday, September 15, 2021 7:14 PM<br>
<b>To:</b> david lounsbury &lt;<a href="mailto:david.lounsbury@einsteinmed.org">david.lounsbury@einsteinmed.org</a>&gt;<br>
<b>Cc:</b> Donrie Purcell &lt;<a href="mailto:donrie.purcell@einsteinmed.org">donrie.purcell@einsteinmed.org</a>&gt;<br>
<b>Subject:</b> Re: Columbia County metrics<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This email comes from an external source; the   attachments and/or links may compromise our secure environment. Do not open   or click on suspicious emails. Please click on the “Phish Alert” button on   the top right of the Outlook dashboard to report any suspicious emails.
--




<p class=MsoNormal>Hello, David. <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<span style='font-size:12.0pt;font-family:"Times New Roman",serif;mso-fareast-font-family:
Calibri;mso-fareast-theme-font:minor-latin;mso-ansi-language:EN-US;mso-fareast-language:
EN-US;mso-bidi-language:AR-SA'>Yes, Lori and Danielle both have IPA entry
responsibilities.&nbsp; Would you like me to do an email intro recapping our
meeting and inviting them to one? &nbsp;</span>
</body>

</html>

**Comment by dlounsbu** [comment]
@donriepurcell 

Please apply your measures analyses to Columbia's data. 

@NBOVE1 

Can you put your fingers on the powerpoint slides that explain present guidance on the recommended structure of a county Action Plan? I will look, too, but I remember Tim presenting about how each Action Plan should have at least3 MOUD strategies, one OEND, and one safe prescribing. And the MOUD strategies should be linkage, initiate, and retain. . . something like that. And then that they should, collectively, touch all three sectors. Right? THANKS

**Comment by NBOVE1** [comment]
Good Morning David, and Donrie.
Sure, I'm attached three documents that directly relate to action planning and are used to train staff on how to properly create an action plan as it relates the HCS and our phase four deliverables. Also, yes the strategies should collectively touch all of three sectors which are behavioral health, healthcare, and criminal justice. If you have any questions, please let me know.
Thanks!
Nick

[PHASE 3 4 5 Training 20200522 REV.pptx](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/7178185/PHASE.3.4.5.Training.20200522.REV.pptx)
[Module 6 Training. CE. Community Action Planning Facilitation.pptx](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/7178187/Module.6.Training.CE.Community.Action.Planning.Facilitation.pptx)
[Action Plan (All Areas) for Members.pdf](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/7178188/Action.Plan.All.Areas.for.Members.pdf)

**Comment by donriepurcell** [comment]
Thanks nick.

Sent from my iPhone

On Sep 16, 2021, at 9:46 AM, NBOVE1 ***@***.***> wrote:

﻿
CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.

Good Morning David, and Donrie.
Sure, I'm attached three documents that directly relate to action planning and are used to train staff on how to properly create an action plan as it relates the HCS and our phase four deliverables. Also, yes the strategies should collectively touch all of three sectors which are behavioral health, healthcare, and criminal justice. If you have any questions, please let me know.
Thanks!
Nick

PHASE 3 4 5 Training 20200522 REV.pptx<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Ffiles%2F7178185%2FPHASE.3.4.5.Training.20200522.REV.pptx&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cd69295b2988b4559eec308d979182b8f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673967707022933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=82Re3LrvNUzuU5yaEB81%2BrRUW2wJHK23liEhIwMoAiA%3D&reserved=0>
Module 6 Training. CE. Community Action Planning Facilitation.pptx<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Ffiles%2F7178187%2FModule.6.Training.CE.Community.Action.Planning.Facilitation.pptx&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cd69295b2988b4559eec308d979182b8f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673967707032921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6NwH5dLOb6ex8YVHA5FhqRjwUCJbT5w3U%2FCx0nbEUjU%3D&reserved=0>
Action Plan (All Areas) for Members.pdf<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Ffiles%2F7178188%2FAction.Plan.All.Areas.for.Members.pdf&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cd69295b2988b4559eec308d979182b8f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673967707032921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1J3VrnHR6ck1JKkQBOuPsxhoDgebO6g0pQQIDN2Moj8%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Fissues%2F31%23issuecomment-920915938&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cd69295b2988b4559eec308d979182b8f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673967707042922%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MXDH9tDVAMfAUFP5tyVK0DWlcS1R3AWjD7DTht7mpSE%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATJKBBLJT6RDP3FX7LXZUYLUCHYFPANCNFSM5DV5QZXQ&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cd69295b2988b4559eec308d979182b8f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673967707042922%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y6%2FeNkZ9gXwjNRpwzM0W7lbAVr0HILlEj4dPXO1VQ4k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cd69295b2988b4559eec308d979182b8f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673967707052907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u8oVGjM5I3lZJ80ACISIhcRE%2BNsj%2B3NUtWgPmmwFX%2Fc%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cd69295b2988b4559eec308d979182b8f%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673967707052907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KD%2FZUgeJQ7e1cXoq5TQYZb5FZk7Y2XYHMPsxQGnHodI%3D&reserved=0>.

**Comment by dlounsbu** [comment]
Thanks very much Nick!

Donrie, let's keep working on useful ways of analyzing and visualizing county-specific Action Plans, with a focus on Measures selected (Step 1 in my proposed outline). 

With that in hand, and before we arrange any follow up with anyone in the county coalition (in this case Columbia Co), we will want to reach out to the county coach (Aimee in this case??), as well as Tim, to explain how we hope to use the information to make recommendations about how to 'clean up' their Tracker data, catch up with monitoring, download data for their own reporting purposes. 

As we have been 'invited' in via Veronica's Tracker TA request, this is an opportunity for use to pilot the protocol steps I outlined the other day. 

Again, I am hoping that this effort on our part will improve the quality of the data being stored in the Tracker for everyone's use. 

Thoughts??

**Comment by donriepurcell** [comment]
sounds good


On Sep 16, 2021, at 10:36 AM, David W Lounsbury ***@***.***> wrote:

﻿
CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.

Thanks very much Nick!

Donrie, let's keep working on useful ways of analyzing and visualizing county-specific Action Plans, with a focus on Measures selected (Step 1 in my proposed outline).

With that in hand, and before we arrange any follow up with anyone in the county coalition (in this case Columbia Co), we will want to reach out to the county coach (Aimee in this case??), as well as Tim, to explain how we hope to use the information to make recommendations about how to 'clean up' their Tracker data, catch up with monitoring, download data for their own reporting purposes.

As we have been 'invited' in via Veronica's Tracker TA request, this is an opportunity for use to pilot the protocol steps I outlined the other day.

Again, I am hoping that this effort on our part will improve the quality of the data being stored in the Tracker for everyone's use.

Thoughts??

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Fissues%2F31%23issuecomment-920960125&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C095bc3e54d6f495a442e08d9791f5eae%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673997915600758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fWRXxmlHji9%2FuwDgoqU3Jym15ydLGxzmSwrK%2B3nzxBM%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATJKBBKRF32BJ6RUOQ5HG2DUCH6GZANCNFSM5DV5QZXQ&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C095bc3e54d6f495a442e08d9791f5eae%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673997915610753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1YOgYwWee1Cb0vcM8qx5aL9nXJ9bcBCzXezX4VJWync%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C095bc3e54d6f495a442e08d9791f5eae%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673997915610753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zehUAlRnXk3yT45K3O0QPMcYwSP232NeSn1Iz46ZFyU%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C095bc3e54d6f495a442e08d9791f5eae%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673997915620747%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GytXCA%2ByN68pIPRavVS1rnIv1P9tj2gkqcsB1K6I1LU%3D&reserved=0>.

**Comment by dlounsbu** [comment]
@donriepurcell when are we scheduled to meet with Lori and Vanessa?!

**Comment by jbazinet1111** [comment]
I see the issue and it has to do with deleting strategies.

For the group: 
What is your policy for retaining monitoring records for strategies and measures that may later get deleted from the specification? Do you want them cleared out or do you want them to remain? If they remain (which is the case now), we may have to jump through some hoops to not show them in the Monitoring.
