### ISSUE TITLE
Service Request by Joshua Powell re remedy allow for data entry field under Other measures 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#52]
**-** [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff
This is pretty **Urgent**!!
Nick and I just took a call from Green County. At the county they up against a deadline of sorts to enter data by a specific date into the tracker.
From all indications they are not able to enter free text on their Other measures from the ORRCA bucket.
Please see below 

![Screen Shot 2021-10-05 at 12 02 00 PM](https://user-images.githubusercontent.com/80912517/136061146-3ca6226e-2ee9-4515-b432-d6497adb40f8.png)

**Comment by jbazinet1111** [comment]
Yes. That functionality was removed per a design request.
________________________________

**Comment by jbazinet1111** [comment]
An administrator can create the measure in the options.
________________________________

**Comment by dlounsbu** [comment]
@jbazinet1111 

Yes, we did ask this of you and thanks for doing it. 

I think the issue is that there are already Other Measures in the system that the county staff want to add Monitoring data for, and somehow they cannot, now. 

For me, the current issue is for us (Admins) to be able add units for any Other Measure that does not have units associated iwth it yet. 

And then, off course, we want the counties to be able to add MONITORING data.

Can you help us sort this out? 

I realize we may be (temporarily) undoing your prior effort. How many hours to for this, Jeff?

Thanks!

**Comment by jbazinet1111** [comment]
You just need to create other measures in the list options whose text exactly matches those that had already been created.

This is what I was referring to with that issue recently where the measures disappeared after she edited them
________________________________

**Comment by donriepurcell** [comment]
Hi Jeff
Please give the counties the ability to adjust their specification data, I believe the need is most acute there.
Thanks

**Comment by jbazinet1111** [comment]
I'm afraid you'll have to expand on that. I'm not sure what you are asking to change.
________________________________

**Comment by dlounsbu** [comment]
@donriepurcell 

Are you saying that users cannot edit ADD/EDIT/DEL an existing strategy, regardless of type (Prim, Sec, Structural or Other)? 

Or is the problem just with ADD/EDIT/DEL an existing Other strategy?

Of course, once the strategy is SPECIFIED, they should be able to add MONITORING data for it, too. Is this working?

**Comment by donriepurcell** [comment]
Basically, we simply want things to return to normal where the counties can enter free text into their other ORCCA bucket selections under **specification** as need be.
Reason being after speaking to county representatives, it is evident that they are still formulating their IPAs and refining issues with their coaches, etc. 
So they will need unfettered access in doing so.
David, Nick and I will now have to figure out how we will regulate the **unit of measurements** for these **other measures** appropriately in **consultation** with you. But free access to data entering they need to have in the moment as you envisioned previously.
Regards 
DONRIE

**Comment by dlounsbu** [comment]
@donriepurcell 

Right. So, Jeff set up a way to for Admins to Download a codebook of all measures, so that it is easy to review what is available and what units have been set up for each measure.

See if you can use this new feature to check that all Measures have a proper unit. 

Regarding the matter of ADD/EDIT/DEL Other measures, we can either do that for the counties, if you can coordinate with them, or we can have Jeff undo that restriction. 

You could work with Nick to send around a message to request a TA to set up a new Other Measure, but if this is overwhelming, we can just go back to how it was before. My only concern is that these new Other Measures may not have units associated with them. So, it is a bit of a catch 22. 

DL

**Comment by jbazinet1111** [comment]
Yes, thanks. This is how it is designed. I haven't done anything with this as I need hours approved to "un-do" the previous design request. 

I'd also suggest that you create the other measures in the list options with the appropriate units so that people can have something to select when they add/edit. Any edits to a measures specification that had an OTHER measure will not be saved properly unless that OTHER measure is added to the options.

**Comment by NBOVE1** [comment]
Note: David has approved hours to "un-do" previous design request. I don't believe there's a need to create other measures in list options as counties will have the ability to enter free text once the change is in place. @donriepurcell we'll discuss this issue further once counties enter all data as they've been requested to do by October 15th.

**Comment by NBOVE1** [comment]
Thank you Jeff, this issue appears to be resolved. I've checked several counties and all can now specify "other" measures using free text. @donriepurcell please let Megan know that her issue should be resolved as well:

![image](https://user-images.githubusercontent.com/88558561/136453640-1ee1f50c-851f-466d-8c2d-9873587d9a9c.png)
