### ISSUE TITLE
Service Request by Kelly  Perry about MONITORING Data in Ulster County (2nd request)

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#64]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
From: Donrie Purcell <donrie.purcell@einsteinmed.org>
Date: Thursday, November 4, 2021 at 9:53 AM
To: david lounsbury <david.lounsbury@einsteinmed.org>, kper@co.ulster.ny.us <kper@co.ulster.ny.us>
Cc: Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: Re: IPA Tracker Support Request Form Submitted
Hi Kelly 

We have created an issue in our system so that we can work with alacrity to resolve the issues you’ve brought forth. If possible can we meet today so we can discuss them further to see where I can best help before I escalate them to the designer of the tracker?

Regards
Donrie Purcell, PhD, MPH

Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

**Comment by donriepurcell** [comment]
Hi Jeff

I am not sure if this is a know how issue. But I am having some trouble removing **3 copy version of F4.3** from the **measures monitoring** section for Ulster County. 
Would you be able to assist you assist with that? 
I think its a remnant from an old IPA.

**Comment by dlounsbu** [comment]
Thanks for looking into this. 

@donriepurcell , did you notice that ALL of Ulster's Strategies are 'Discontinued'? 

Why is that? Did a user set them that way, or not? 

@jbazinet1111 , Can you explain, again, what happens when a strategy is discontinued vs. deleted?

I think that when a strategy is discontinued, prior monitoring data, if it exists, should remain. But prompting for new monitoring data should stop. 

And, if a strategy is deleted, then all specification and monitoring data for that strategy should be removed (erased) from data tables.

Thanks to you both.
